### ISSUE TITLE
How did you get the drop shadow on the screenshot?

### ISSUE THREAD

**Issue by sdushantha** [andreyorst/dotfiles#3]
How did you get the very nice shadow behind the window in the screenshot?
![](https://user-images.githubusercontent.com/19470159/38469407-c927caa4-3b5c-11e8-8832-17a02992bf78.png)

Imagemagick?

**Comment by andreyorst** [comment]
KDE Spectacle can take screenshot of a window with its shadow.
Gnome Screenshot can add shadow as a post effect. This screenshot was made with Spectacle

**Comment by sdushantha** [comment]
Oh okay. I wish there was a script or something which would add this effect to a screenshot, it looks very nice. 

But thanks thought :smile:
