### ISSUE TITLE
How did you generate file header in language.kak

### ISSUE THREAD

**Issue by ratheesh** [andreyorst/dotfiles#4]
May I know how did you generate the header table in the file `https://github.com/andreyorst/dotfiles/.config/kak/languages.kak`
It looks really nice!

**Comment by andreyorst** [comment]
![case](https://user-images.githubusercontent.com/19470159/59425043-d3126e00-8ddd-11e9-803f-9729b8c3f1a6.gif)

By hands, unfortunately

**Comment by ratheesh** [comment]
Thanks!
