### ISSUE TITLE
tab-line-tab-current

### ISSUE THREAD

**Issue by Compro-Prasad** [andreyorst/dotfiles#5]
```elisp
(set-face-attribute 'tab-line-tab-current nil :foreground fg :background bg :box (list :line-width box-width :color bg) :weight 'normal :inherit nil)
```
doesn't work. Your config is super awesome. I have some area of improvement that I have in my config. Will you accept PRs?

Also, why is your magit status buffer lagging on keypress. It worked good after disabling `tab-line-mode`.

**Comment by andreyorst** [comment]
They keep changing tabline face names in Emacs 27 master branch. I'm trying to keep up, but I don't update Emacs every day, so maybe the name was changed again. 

> I have some area of improvement that I have in my config. Will you accept PRs?

I'll definitively will give a look. Performance improvements are always welcome, however, I try to keep my configuration close to the vanilla, yet personal as well.

> Also, why is your magit status buffer lagging on keypress. It worked good after disabling tab-line-mode.

I.. have no lag in magit.. What lags do you experience?

**Comment by andreyorst** [comment]
Just checked. On the latest master of Emacs 27 this face is named `tab-line-tab-current`. Maybe you should update your Emacs?

**Comment by Compro-Prasad** [comment]
That fixed it. Thanks.
